// Configuration file for API keys and sensitive information
const config = {
    GEMINI_API_KEY: 'YOUR_GEMINI_API_KEY_HERE',
    FIREBASE_API_KEY: 'YOUR_FIREBASE_API_KEY_HERE',
    FIREBASE_AUTH_DOMAIN: 'YOUR_FIREBASE_AUTH_DOMAIN_HERE',
    FIREBASE_PROJECT_ID: 'YOUR_FIREBASE_PROJECT_ID_HERE',
    FIREBASE_STORAGE_BUCKET: 'YOUR_FIREBASE_STORAGE_BUCKET_HERE',
    FIREBASE_MESSAGING_SENDER_ID: 'YOUR_FIREBASE_MESSAGING_SENDER_ID_HERE',
    FIREBASE_APP_ID: 'YOUR_FIREBASE_APP_ID_HERE',
    CLOUDINARY_CLOUD_NAME: 'YOUR_CLOUDINARY_CLOUD_NAME_HERE',
    CLOUDINARY_API_KEY: 'YOUR_CLOUDINARY_API_KEY_HERE',
    CLOUDINARY_API_SECRET: 'YOUR_CLOUDINARY_API_SECRET_HERE'
};

export default config; 